{
 "title": "Cross-Cloud Workload Health",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "AWS - ALB Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/multicloud-task3-alb/4ed41f7f69e912ab"
     },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Azure - App Gateway Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "aggregation": "Total",
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "region": "uksouth",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "uksouth",
        "resourceGroup": "rg-multicloud-portfolio",
        "resourceName": "app-multicloud-task4",
        "subscription": "81197388-0d27-49a4-a47d-91730e333ca2"
       }
      ],
      "timeGrain": "auto"
     },
     "metricName": "TotalRequests",
     "resourceUri": "/subscriptions/81197388-0d27-49a4-a47d-91730e333ca2/resourceGroups/rg-multicloud-portfolio/providers/Microsoft.Network/applicationGateways/appgw-multicloud-task4",
     "subscription": "81197388-0d27-49a4-a47d-91730e333ca2"
    }
   ]
  },
  {
   "title": "AWS - ASG In-Service Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "multicloud-task3-asg" },
     "metricName": "GroupInServiceInstances",
     "namespace": "AWS/AutoScaling",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Azure - App Service CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "aggregation": "Total",
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuTime",
      "metricNamespace": "microsoft.web/sites",
      "region": "uksouth",
      "resources": [
       {
        "metricNamespace": "Microsoft.Web/sites",
        "region": "uksouth",
        "resourceGroup": "rg-multicloud-portfolio",
        "resourceName": "app-multicloud-task4",
        "subscription": "81197388-0d27-49a4-a47d-91730e333ca2"
       }
      ],
      "timeGrain": "auto"
     },
     "metricName": "CpuTime",
     "resourceUri": "/subscriptions/81197388-0d27-49a4-a47d-91730e333ca2/resourceGroups/rg-multicloud-portfolio/providers/Microsoft.Web/sites/app-multicloud-task4",
     "subscription": "81197388-0d27-49a4-a47d-91730e333ca2"
    }
   ]
  }
 ]
}