{
 "title": "Cross-Cloud Workload Health",
 "panels": [
  {
   "title": "AWS - ALB Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "namespace": "AWS/ApplicationELB",
     "metricName": "RequestCount",
     "statistic": "Sum",
     "dimensions": {
      "LoadBalancer": "app/multicloud-task3-alb/4ed41f7f69e912ab"
     }
    }
   ]
  },
  {
   "title": "Azure - App Gateway Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "resourceUri": "/subscriptions/81197388-0d27-49a4-a47d-91730e333ca2/resourceGroups/rg-multicloud-portfolio/providers/Microsoft.Network/applicationGateways/appgw-multicloud-task4",
     "metricName": "TotalRequests",
     "aggregation": "Total"
    }
   ]
  },
  {
   "title": "AWS - ASG In-Service Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "namespace": "AWS/AutoScaling", "metricName": "GroupInServiceInstances", "statistic": "Average", "dimensions": { "AutoScalingGroupName": "multicloud-task3-asg" } }
   ]
  },
  {
   "title": "Azure - App Service CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "resourceUri": "/subscriptions/81197388-0d27-49a4-a47d-91730e333ca2/resourceGroups/rg-multicloud-portfolio/providers/Microsoft.Web/sites/app-multicloud-task4",
     "metricName": "CpuTime",
     "aggregation": "Total"
    }
   ]
  }
 ]
}